version: '3'
services:
  broker:
    image: "redis:5.0.5-alpine3.9"
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Sao_Paulo
      - COUNTER=${COUNTER}
    depends_on:
      - broker
